# Generated by Django 3.0.7 on 2020-06-17 22:33

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50, unique=True)),
                ('graph_info', models.TextField()),
                ('initial_cyjs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('layouts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
                ('styles', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50, unique=True)),
                ('abstract', models.TextField(blank=True)),
                ('content_md', models.TextField(verbose_name='markdown tutorial')),
                ('content_html', models.TextField(verbose_name='HTML tutorial')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='backend.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Tutorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphInitialCodeExecResultJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TutorialCode')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Graph')),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='tutorial',
            field=models.ManyToManyField(to='backend.Tutorial'),
        ),
        migrations.AddConstraint(
            model_name='tutorial',
            constraint=models.UniqueConstraint(fields=('id', 'url'), name='tutorial id_url constraint'),
        ),
        migrations.AddConstraint(
            model_name='graphinitialcodeexecresultjson',
            constraint=models.UniqueConstraint(fields=('code', 'graph'), name='code graph constraint'),
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.UniqueConstraint(fields=('id', 'url'), name='graph id_url constraint'),
        ),
    ]
