# Generated by Django 3.0.7 on 2020-06-17 22:00

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_timedatemixin_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('graph_info', models.TextField()),
                ('initial_cyjs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('layouts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
                ('styles', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
                ('tutorial', models.ManyToManyField(to='backend.Tutorial')),
            ],
        ),
    ]
