# Generated by Django 3.0.7 on 2020-06-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200617_2233'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='graph',
            name='graph id_url constraint',
        ),
        migrations.RemoveConstraint(
            model_name='graphinitialcodeexecresultjson',
            name='code graph constraint',
        ),
        migrations.RemoveConstraint(
            model_name='tutorial',
            name='tutorial id_url constraint',
        ),
        migrations.AddField(
            model_name='graph',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='unclassified', max_length=30, unique=True),
        ),
        migrations.AddConstraint(
            model_name='graphinitialcodeexecresultjson',
            constraint=models.UniqueConstraint(fields=('code', 'graph'), name='code exec result constraint'),
        ),
    ]
