# Generated by Django 3.0.7 on 2020-06-18 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200618_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZHCN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('content_md', models.TextField()),
                ('content_html', models.TextField()),
                ('translator', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Tutorial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
