# Generated by Django 3.0.7 on 2020-06-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_zhcn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='uncategorized', max_length=30, unique=True),
        ),
    ]
