# Generated by Django 3.0.7 on 2020-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200618_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zhcn',
            old_name='tutorial',
            new_name='original_tutorial',
        ),
        migrations.AddField(
            model_name='zhcn',
            name='abstract',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
