# Generated by Django 3.0.7 on 2020-06-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200618_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(60, 'Administrator'), (40, 'author'), (20, 'translator'), (0, 'visitor')], default=0, max_length=2),
        ),
    ]
