# Generated by Django 3.0.7 on 2020-06-18 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200618_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zhcn',
            old_name='translator',
            new_name='authors',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='content_md',
        ),
        migrations.CreateModel(
            name='ENUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('abstract', models.TextField()),
                ('content_md', models.TextField()),
                ('content_html', models.TextField()),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('original_tutorial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Tutorial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
