# Generated by Django 3.0.7 on 2020-06-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200618_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enus',
            old_name='original_tutorial',
            new_name='tutorial_anchor',
        ),
        migrations.RenameField(
            model_name='zhcn',
            old_name='original_tutorial',
            new_name='tutorial_anchor',
        ),
    ]
