# Generated by Django 3.0.7 on 2020-06-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='backend_cat_categor_cfa311_idx',
        ),
        migrations.RemoveIndex(
            model_name='graph',
            name='backend_gra_url_310160_idx',
        ),
        migrations.RemoveIndex(
            model_name='tutorial',
            name='backend_tut_url_b279e5_idx',
        ),
        migrations.AlterField(
            model_name='graph',
            name='url',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='url',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
