# Generated by Django 3.0.7 on 2020-06-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200622_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='url',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='url',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
