# Generated by Django 3.0.7 on 2020-07-05 20:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_execresultjson_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='graph_info',
        ),
        migrations.CreateModel(
            name='ZHCNGraph',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('graph_anchor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ENUSGraph',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('graph_anchor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Graph')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
