# Generated by Django 3.0.7 on 2020-07-05 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200705_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='enusgraph',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enusgraph',
            name='title',
            field=models.CharField(default='default-title', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zhcngraph',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zhcngraph',
            name='title',
            field=models.CharField(default='default-title', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
