# Generated by Django 3.0.8 on 2020-07-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200705_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ENUSGraph',
            new_name='ENUSGraphContent',
        ),
        migrations.RenameModel(
            old_name='ZHCNGraph',
            new_name='ZHCNGraphContent',
        ),
    ]
