# Generated by Django 3.0.8 on 2020-07-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_uploads_tutorial_anchor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='tutorial_anchor',
        ),
        migrations.AddField(
            model_name='uploads',
            name='link_id',
            field=models.UUIDField(default='3e8c3a27-bb56-4dd2-92a1-069c26b533e4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploads',
            name='where',
            field=models.CharField(choices=[('TR', 'Tutorial'), ('GR', 'Graph')], default='TR', max_length=2),
        ),
    ]
