# Generated by Django 3.0.8 on 2020-07-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200731_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='enusgraphcontent',
            name='abstract_md',
            field=models.TextField(default='# default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zhcngraphcontent',
            name='abstract_md',
            field=models.TextField(default='# default'),
            preserve_default=False,
        ),
    ]
