# Generated by Django 3.0.8 on 2020-08-01 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200731_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='tutorial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.Tutorial'),
        ),
        migrations.AlterField(
            model_name='enus',
            name='tutorial_anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.Tutorial'),
        ),
        migrations.AlterField(
            model_name='enusgraphcontent',
            name='graph_anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.Graph'),
        ),
        migrations.AlterField(
            model_name='zhcn',
            name='tutorial_anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.Tutorial'),
        ),
        migrations.AlterField(
            model_name='zhcngraphcontent',
            name='graph_anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.Graph'),
        ),
    ]
