# Generated by Django 3.0.8 on 2020-08-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200801_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='where',
        ),
    ]
