# Generated by Django 3.0.8 on 2020-08-08 22:25

from django.db import migrations, models


def generate_default_alias(apps, schema_editor):
    upload_model = apps.get_model('backend', 'Uploads')
    i = 0
    for model_instance in upload_model.objects.all():
        model_instance.alias = f'default_{i}'
        i += 1
        model_instance.save(update_fields=['alias'])


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200803_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='alias',
            field=models.TextField(default='default', null=True),
        ),
        migrations.RunPython(generate_default_alias),
        migrations.AlterField(
            model_name='uploads',
            name='alias',
            field=models.TextField(unique=True, null=False)
        )
    ]
