# Generated by Django 3.0.8 on 2020-08-18 02:45

from django.db import migrations, models


def generate_default_class_number(apps, _):
    tutorial_model: models.Model = apps.get_model('backend', 'Tutorial')
    i = 101
    for model_instance in tutorial_model.objects.all():
        model_instance.level = i
        i += 1
        model_instance.save(update_fields=['level'])


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_uploads_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='section',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.RunPython(generate_default_class_number),
        migrations.AlterField(
            model_name='tutorial',
            name='level',
            field=models.PositiveSmallIntegerField(unique=True),
        )
    ]
