# Generated by Django 3.0.8 on 2020-08-27 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_reset_rank_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='execresultjson',
            name='breakpoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), default=list, size=None),
        ),
    ]
