# Generated by Django 3.1.4 on 2021-01-02 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_adapt_json_field_to_django_3_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGraphContent',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abstract_md', models.TextField()),
                ('abstract', models.TextField()),
                ('graph_anchor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ES',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('abstract', models.TextField()),
                ('content_md', models.TextField()),
                ('content_html', models.TextField()),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tutorial_anchor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.tutorial')),
            ],
            options={
                'verbose_name': 'ES translation',
            },
        ),
    ]
