# Generated by Django 3.1.4 on 2021-01-04 22:57

import django.core.management.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_es_esgraphcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCodeModel',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_code', models.CharField(default=django.core.management.utils.get_random_secret_key, max_length=200, unique=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('expiration_times', models.IntegerField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(60, 'Administrator'), (40, 'Author'), (20, 'Translator'), (0, 'Visitor')])),
            ],
            options={
                'verbose_name': 'Invitation code',
            },
        ),
        migrations.AlterModelOptions(
            name='enusgraphcontent',
            options={'verbose_name': 'EN-US graph content'},
        ),
        migrations.AlterModelOptions(
            name='esgraphcontent',
            options={'verbose_name': 'ES graph content'},
        ),
        migrations.AlterModelOptions(
            name='zhcngraphcontent',
            options={'verbose_name': 'ZH-CN graph content'},
        ),
        migrations.AddConstraint(
            model_name='invitationcodemodel',
            constraint=models.CheckConstraint(check=models.Q(('expiration_date__isnull', True), ('expiration_times__isnull', True), _negated=True), name='has expiration date or expiration times'),
        ),
    ]
