# Generated by Django 3.1.5 on 2021-01-07 18:37

from django.db import migrations, models


def generate_default_name(apps, schema_editor):
    upload_model = apps.get_model('backend', 'Code')
    i = 0
    for model_instance in upload_model.objects.all():
        model_instance.name = f'default_name_{i}'
        i += 1
        model_instance.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210104_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(default='2021-01-07 18:37:15.758732+00:00', max_length=300),
            preserve_default=False,
        ),
        migrations.RunPython(generate_default_name),
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=300, null=False, blank=False, unique=True)
        )
    ]
