<template>
  <div class="full-height">
    <q-bar class="graph-menu-bar">
      <div class="graph-menu-wrapper">
        <q-select
          class="graph-selector"
          :options="getGraphObjectList"
          v-model="graphChoice"
          label="Graph"
          :multiple="false"
          dropdown-icon="mdi-menu-down"
          :loading="selectLoading"
          :option-label="inputSectionLabelMapper"
          option-value="id"
          emit-value
          map-options
        >
          <template v-slot:no-option>
            <q-item>
              <q-item-section class="text-grey">
                No results
              </q-item-section>
            </q-item>
          </template>
          <template v-slot:prepend>
            <q-icon name="mdi-graphql"></q-icon>
          </template>
        </q-select>
      </div>
      <div class="menu-button-group-wrapper">
        <q-btn-group rounded flat class="menu-button-group q-mx-auto">
          <q-btn-dropdown>
            <template v-slot:label>
              <q-icon name="mdi-share-variant" />
              <SwitchTooltip :text="$t('tooltips.Share')"></SwitchTooltip>
            </template>
            <q-list>
              <!-- share graph json -->
              <q-item clickable v-close-popup @click="shareGraphJson">
                <q-item-section avatar>
                  <q-avatar icon="mdi-code-json" />
                </q-item-section>
                <q-item-section>
                  <q-item-label>Share Json</q-item-label>
                  <q-item-label caption>
                    Copy the json of this graph
                  </q-item-label>
                </q-item-section>
              </q-item>
              <!-- share graph screen shot -->
              <q-item clickable v-close-popup @click="shareGraphScreenshot">
                <q-item-section avatar>
                  <q-avatar icon="photo" />
                </q-item-section>
                <q-item-section>
                  <q-item-label>Share Screenshot</q-item-label>
                  <q-item-label caption>
                    Copy the screenshot of this graph
                  </q-item-label>
                </q-item-section>
              </q-item>
            </q-list>
          </q-btn-dropdown>
        </q-btn-group>
      </div>
    </q-bar>
    <div id="cy-wrapper" :style="heightStyle">
      <div id="cy" class="full-height" :style="graphStyle" ref="cy"></div>
    </div>
    <div>
      <q-inner-loading
        :showing="graphObjectListEmpty || libLoading"
        transition-show="fade"
        transition-hide="fade"
      >
        <q-spinner-pie size="64px" color="primary" />
      </q-inner-loading>
    </div>
  </div>
</template>

<script>
  import Vue from 'vue';
  let cytoscape;
  let panzoom;
  let dagre;
  let fcose;
  let Tippy;
  let TippySticky;
  let popper;
  let lasso;

  import { graphMenuHeaderSize } from '@/store/states/meta';
  import { mapState, mapGetters } from 'vuex';
  import { panzoomDefaults, GraphLayout } from './config.js';

  import {
    saveToFile,
    jpegMIMEType,
    jsonMIMEType,
    errorDialog,
    successDialog,
  } from '@/services/helpers';
  import CytoscapeManager from '@/components/framework/GraphEditorControls/CytoscapeManager';
  import TippyComponent from '@/components/framework/TippyComponents/TippyComponent';

  const tippyComponentClass = Vue.extend(TippyComponent);

  export default {
    mixins: [CytoscapeManager],
    components: {
      SwitchTooltip: () => import('@/components/framework/SwitchTooltip.vue'),
    },
    props: {
      selectLoadingOverride: {
        type: Boolean,
        default: false,
      },
    },
    data() {
      return {
        cyInstance: null,
        moduleLoadedNum: 0,
        moduleTargetNum: 6,
        tippy: null,
        testValue: 0,
        lastVarObjectStore: {},
        accessedVarObjectStore: [],
        choseGraphObj: null,
        // TODO remember to clear this out
      };
    },
    computed: {
      ...mapState('settings', [
        'hideEdgeWhenRendering',
        'renderViewportOnly',
        'motionBlurEnabled',
        'motionSensitivityLevel',
      ]),
      // TODO watch to every cy options
      ...mapGetters('settings', ['graphBackgroundColor']),
      ...mapGetters('graphs', [
        'getCurrentGraphId',
        'getGraphObjectList',
        'graphObjectListEmpty',
        'autoGeneratedCurrentGraphObject',
        'autoGeneratedCurrentGraphJsonObj',
      ]),
      cytoscape_() {
        return this.cyInstance;
      },
      graphChoice: {
        get() {
          return this.choseGraphObj;
        },
        set(choseGraphObj) {
          if (choseGraphObj && choseGraphObj !== this.choseGraphObj) {
            this.choseGraphObj = choseGraphObj;

            this.$store.commit('graphs/LOAD_CURRENT_GRAPH_ID', choseGraphObj);
          }
        },
      },
      libLoading() {
        return this.moduleLoadedNum < this.moduleTargetNum;
      },
      selectLoading() {
        return this.graphObjectListEmpty || this.selectLoadingOverride;
      },
      graphStyle() {
        return {
          'background-color': this.graphBackgroundColor,
        };
      },
      heightStyle() {
        return {
          height: `calc(100% - ${graphMenuHeaderSize}px)`,
        };
      },
    },
    methods: {
      moduleLoad() {
        this.moduleLoadedNum += 1;
      },
      registerExtensions() {
        import('cytoscape-panzoom').then((pz) => {
          console.debug('cytoscape panzoom module: ', pz);
          panzoom = pz.default;

          if (typeof cytoscape('core', 'panzoom') !== 'function') {
            cytoscape.use(panzoom);
          }

          this.cyInstance.panzoom(panzoomDefaults);

          this.$nextTick(() => {
            this.resizeGraph();
          });

          this.moduleLoad();
        });

        import('cytoscape-dagre').then((cd) => {
          console.debug('cytoscape dagre module: ', cd);
          dagre = cd.default;

          cytoscape.use(dagre);

          this.updateLayout();
          this.moduleLoad();
        });

        import('cytoscape-fcose').then((cf) => {
          console.debug('cytoscape fcose module: ', cf);
          fcose = cf.default;

          cytoscape.use(fcose);

          this.updateLayout();
          this.moduleLoad();
        });

        import('cytoscape-popper')
          .then((pp) => {
            console.debug('cytoscape popper module: ', pp);

            popper = pp.default;
            if (typeof cytoscape('core', 'popper') !== 'function') {
              cytoscape.use(popper);
            }
            this.moduleLoad();
          })
          .then(() => {
            import('tippy.js')
              .then((tp) => {
                console.debug('Tippy module: ', tp);
                Tippy = tp.default;
                TippySticky = tp.sticky;
                this.moduleLoad();
              })
              .then(() => {
                this.setupTooltips(this.cyInstance);
              });
          });

        import('cytoscape-lasso').then((ls) => {
          console.debug('cytoscape lasso module', ls);

          lasso = ls.default;
          cytoscape.use(lasso);
          this.cyInstance.lassoSelectionEnabled(true);

          this.moduleLoad();
        });
      },
      makeTippy(node, componentPropData) {
        const ref = node.popperRef();
        const dummyDomEle = document.createElement('div');
        const tc = new tippyComponentClass({
          propsData: componentPropData,
        }).$mount();

        return new Tippy(dummyDomEle, {
          getReferenceClientRect: ref.getBoundingClientRect,
          // https://atomiks.github.io/tippyjs/v6/all-props/#getreferenceclientrect
          trigger: 'manual',
          // mandatory, we cause the tippy to show programmatically.

          // dom element inside the tippy:
          content: () => {
            const c = document.createElement('div');
            c.appendChild(tc.$el);
            return c;
          },

          // your own preferences:
          arrow: true,
          placement: 'bottom',
          theme: 'light',
          hideOnClick: 'true',
          delay: [650, 200],
          animation: 'fade',
          duration: [250, 275],
          allowHTML: true,
          touch: true,
          interactive: true,
          sticky: true,
          plugins: [TippySticky],
          maxWidth: 500,
          interactiveBorder: 4,

          appendTo: document.body, // or append dummyDomEle to document.body
        });
      },
      closeTippy() {
        if (this.tippy !== null) {
          this.tippy.destroy();
        }
      },
      setupTooltips(instance) {
        // show node tooltips
        instance.on('mouseover', 'node', (event) => {
          const node = event.target;
          const nodeData = node.data();
          this.tippy = this.makeTippy(node, {
            initElement: {
              name: nodeData['name'],
            },
          });
          this.tippy.show();
        });
        instance.on('mouseout', 'node', () => {
          this.closeTippy();
        });

        // show edge tooltips
        instance.on('mouseover', 'edge', (event) => {
          const node = event.target;
          const nodeData = node.data();
          this.tippy = this.makeTippy(node, {
            initElement: {
              name: nodeData['name'],
            },
          });
          this.tippy.show();
        });

        instance.on('mouseout', 'edge', () => {
          this.closeTippy();
        });
      },
      restoreStyles() {
        this.clearStoredClassNames();
      },
      reloadCyWithFullJson(json) {
        if (this.cyInstance && json) {
          this.cyInstance.elements().remove();
          this.cyInstance.add(json.elements);
          if (json.style) {
            this.cyInstance
              .style()
              .resetToDefault()
              .fromJson(this.defaultGraphStyle)
              .update();
            this.addStyle(json.style);
          }
          this.clearStoredClassNames();
        }
      },
      // highlight helper function
      highlightElementByClass(varName, varObj) {
        if (!this.cyInstance) {
          return;
        }
        const className = varName;
        const elementId = varObj.id;
        const elementColor = varObj.color;
        if (!this.storedClassNames.includes(className)) {
          this.generateColoredClass(className, elementColor);
        }
        this.addClassNameById(elementId, className);
      },
      // clear highlight interface
      clearHighLightByClass(bareClassName) {
        this.removeElementsClassName(bareClassName);
      },
      // toggle highlight interface
      toggleHighlight(ids, bareClassName, flag) {
        if (ids && bareClassName) {
          this.toggleElementsByIds(ids, bareClassName, flag);
        }
      },
      // highlight interface
      highlightByClassAndIds(className, elementIds, color) {
        if (elementIds && color) {
          this.generateColoredClass(className, color);
          this.addClassNameByIds(className, elementIds);
        }
      },
      currentGraphLayoutOption() {
        if (this.autoGeneratedCurrentGraphJsonObj === null) {
          return null;
        }

        if (this.autoGeneratedCurrentGraphJsonObj.layout) {
          return (
            GraphLayout[this.autoGeneratedCurrentGraphJsonObj.layout.name] ||
            GraphLayout.preset
          );
        }

        return GraphLayout.fcose;
      },
      reloadGraph() {
        if (this.cyInstance) {
          this.cyInstance.style().resetToDefault();
          this.reloadCyWithFullJson(this.autoGeneratedCurrentGraphJsonObj);
          this.updateLayout();
        }
      },
      updateLayout() {
        if (!this.cyInstance) {
          return;
        }

        this.layoutOptions = this.currentGraphLayoutOption();
        this.runLayout(this.cyInstance, this.layoutOptions);
      },
      runLayout(instance, layoutOptions = null) {
        /**
         * Runs the current layout.
         * @param {cytoscape} instance - the cytoscape instance
         * @param {*} [layoutOptions=null] - the layout options
         * @return {boolean} true if the layout ran successfully, false otherwise (e.g. manually stopped, temperature drop, etc)
         * @see {@link https://js.cytoscape.org/#cy.layout}
         * @see {@link https://github.com/cylc/cylc-ui/blob/master/src/components/cylc/graph/Graph.vue}
         */
        try {
          return instance
            .elements()
            .layout(layoutOptions || this.layoutOptions)
            .run();
        } catch (_) {
          // This is ignored, but can still be captured in the browser console, by checking the option to break on
          // exceptions, even if captured.
          //
          // The reason we need this, is that if the user has multiple components being displayed, and then closes one
          // of them while this code is running, it may cause an error saying that the layout is empty.
          // There is no action that we, or the user, can perform upon such error. Hence this being ignored.
        }
        return false;
      },
      /**
       * Triggers a graph resize, forcing it to repaint itself. Useful when the graph nodes and edges have been
       * modified, or when an older browser doesn't render the graph until it is resized.
       * @see https://github.com/cytoscape/cytoscape.js/issues/1748
       */
      resizeGraph() {
        if (this.cyInstance) {
          this.cyInstance.resize();
        }
      },
      shareGraphJson() {
        if (this.cyInstance) {
          saveToFile(
            'graph.json',
            JSON.stringify(this.cyInstance.json(), null, 2),
            jsonMIMEType
          );
          successDialog({ message: 'Json downloaded.' });
        } else {
          errorDialog({
            message: 'The Cytoscape instance is not ready. Nothing is saved.',
          });
        }
      },
      shareGraphScreenshot() {
        if (this.cyInstance) {
          saveToFile(
            'graph.jpg',
            this.cyInstance.jpg({ output: 'blob' }),
            jpegMIMEType
          );
          successDialog({ message: 'Image downloaded.' });
        } else {
          errorDialog({
            message: 'The Cytoscape instance is not ready. Nothing is saved.',
          });
        }
      },
      loadFirstGraph() {
        if (this.getGraphObjectList && this.getGraphObjectList.length > 0) {
          this.graphChoice = this.getGraphObjectList[0].id;
        }

        this.graphChoice = null;
      },
      inputSectionLabelMapper(obj) {
        return Object(obj) === obj && 'content' in obj
          ? obj.content.title === '<None>'
            ? 'No Title'
            : obj.content.title
          : null;
      },
    },
    watch: {
      getGraphObjectList: function() {
        this.loadFirstGraph();
      },
      autoGeneratedCurrentGraphObject: function() {
        this.reloadGraph();
      },
    },
    mounted() {
      import('cytoscape')
        .then((cy) => {
          // async load cytoscape
          cytoscape = cy.default;

          console.debug('cytoscape module: ', cy);
        })
        .then(() => {
          // start init

          const element = document.createElement('div');
          element.setAttribute('id', 'cy-mounting-point');
          element.setAttribute('class', 'cytoscape');
          element.setAttribute('class', 'full-height');

          this.$refs.cy.appendChild(element);

          /*
           * When passing objects to Cytoscape.js for creating elements, animations, layouts, etc.,
           * the objects are considered owned by Cytoscape. __** this may cause conflicts when working with vuex **__
           * When desired, the programmer can copy objects manually before passing them to Cytoscape. However,
           * copying is not necessary for most programmers most of the time.
           *
           * cannot use get element by id
           * NOTE: Vue will try to create observers for each property in this nested cytoscape object
           *       and it crashed my browser several times. By freezing it, we tell Vue to not bother
           *       about it. This isn't a reactive property anyway, just a variable in the component.
           *
           */

          this.cyInstance = Object.freeze(
            cytoscape({
              container: element,
              // animation settings
              textureOnViewport: this.renderViewportOnly,
              hideEdgesOnViewport: this.hideEdgeWhenRendering,
              motionBlur: this.motionBlurEnabled,
              zoom: 1,
              styleEnabled: true,
            })
          );

          this.loadFirstGraph();
          this.reloadGraph();

          // Force it to be painted again, so that when added to the DOM it doesn't show a blank graph
          this.$nextTick(() => {
            this.resizeGraph();
          });

          this.moduleLoad();

          this.$emit('cytoscapeInstanceLoaded');
        })
        .then(() => {
          this.registerExtensions();
        })
        .catch((error) => {
          errorDialog({
            message:
              'An error occurs during initializing Cytoscape (Graph Section). ' +
              error,
          });
        });
    },
    beforeDestroy() {
      this.closeTippy();
    },
  };
</script>

<style lang="sass">
  @import '~@/styles/panzoom.css'
  @import '~tippy.js/dist/tippy.css'
  @import "~tippy.js/themes/light.css"

  .graph-menu-bar
    min-height: 56px
    max-height: 56px
    display: flex
    flex-direction: row
    .graph-menu-wrapper
      padding: 0 5px
      margin: 0 15px
      min-width: 50%
      max-height: inherit

    .menu-button-group-wrapper
      margin: auto 5px
</style>
