<script>
  import {
    errorDialog,
    notAvailableMessage,
    saveTextToClipboard,
    successDialog,
  } from '@/services/helpers';
  import ResultJsonManager from '@/components/framework/GraphEditorControls/ResultJsonManager';
  import CodeManager from '@/components/framework/GraphEditorControls/CodeManager';
  import GraphManager from '@/components/framework/GraphEditorControls/GraphManager';
  import PushCodeToLocalMixin from '@/components/mixins/PushCodeToLocalMixin';
  import { VARIABLE_EMPTY_CONTENT_NOTATION } from '@/components/framework/GraphEditorControls/parameters';

  export default {
    mixins: [
      ResultJsonManager,
      CodeManager,
      GraphManager,
      PushCodeToLocalMixin,
    ],
    data() {
      return {
        loadedList: {
          editor: false,
          cytoscape: false,
        },
      };
    },
    computed: {
      disableSelection() {
        return this.isExecutingLocally;
      },
      editorControlSliderPosition() {
        return this.getResultJsonPositionObject(this.currentPositionId);
      },
      editorControlSliderLength() {
        return this.currentJsonObject || this.currentJsonObject === []
          ? this.currentJsonObject.jsonObject.length
          : 1;
      },
    },
    methods: {
      emptyVariables(element) {
        return element['variables'] === VARIABLE_EMPTY_CONTENT_NOTATION;
      },
      onSliderChange(newPosition) {
        const positionDelta =
          newPosition -
          this.getResultJsonPositionFromId(this.currentPositionId);
        this.stepper(newPosition, positionDelta);
        // this.updateResultJsonPosition(this.currentPositionId, pos);
      },
      updateEditorLine(lineNumber) {
        if (this.$refs.editorWrapper) {
          this.$refs.editorWrapper.editorMoveLine(lineNumber);
        }
      },
      findLastNoneEmptyElementPos(pos) {
        // pos: number
        for (let i = pos; i >= 0; i--) {
          const element = this.getResultJsonObjectElement(
            { graphId: this.currentGraphId, codeId: this.currentCodeId },
            i
          );
          if (!this.emptyVariables(element)) {
            return element;
            // TODO what's the first element?
          }
        }
        // return number
      },
      singleStep(element) {
        // element: {line: number, variables: object}

        if (!this.emptyVariables(element)) {
          this.viewUpdater(element);
        }
      },
      multipleSteps(noneEmptyElement) {
        this.viewUpdater(noneEmptyElement);
      },
      updateCytoscapeView(variables) {
        if (this.$refs.cytoscapeWrapper) {
          this.$refs.cytoscapeWrapper.highlightVarObj(variables);
        }
      },
      updateVariableList(variables) {
        this.$store.commit('variables/LOAD_CURRENT_VARIABLES', variables);
      },
      viewUpdater(element) {
        // elements: non null
        const variables = element['variables'];
        this.updateVariableList(variables);
        this.updateCytoscapeView(variables);
      },
      stepper(newPosition, steps) {
        console.log('stepper new position', newPosition);

        this.updateResultJsonPosition(this.currentPositionId, newPosition);
        const element = this.getResultJsonObjectElement(
          { graphId: this.currentGraphId, codeId: this.currentCodeId },
          newPosition
        );

        if (!element) {
          return;
        }

        this.updateEditorLine(element['line']);

        if (steps === 1 || steps === -1) {
          console.log('stepper element', element);
          this.singleStep(element);
        } else {
          const noneEmptyElement = this.findLastNoneEmptyElementPos(
            newPosition
          );
          console.log('none empty element', noneEmptyElement);
          this.multipleSteps(noneEmptyElement);
        }
      },
      restartWithNewPosition(pos) {
        if (pos) {
          this.$refs.editorControlUnit.setPositionValueCopyFromJsonPos(pos);
          this.stepper(pos, pos);
        }
      },
      resetContent() {
        const newPosition = this.getResultJsonPositionFromId(
          this.currentPositionId
        );
        this.restartWithNewPosition(newPosition);
      },
      onPushToCloudExec() {
        notAvailableMessage();
      },
      onPushToLocalExec() {
        const editorWrapper = this.checkEditorInitialized(true);

        if (editorWrapper) {
          this.pushToLocal(
            editorWrapper.getCurrentCode(),
            this.$store.getters['graphs/autoGeneratedCurrentGraphJsonObj'],
            () => {
              this.restartWithNewPosition(0);
            },
            (codeHash, execResult) => {
              this.$store.commit('rj/CHANGE_RESULT_JSON_OBJECT', {
                jsonObject: execResult,
                graphId: this.currentGraphId,
                codeId: this.currentCodeId,
              });
              this.$store.commit('rj/CHANGE_RESULT_JSON_STRING', {
                json: JSON.stringify(execResult),
                graphId: this.currentGraphId,
                codeId: this.currentCodeId,
              });
            },
            () => null
          );
        }
      },
      checkEditorInitialized(showErrorDialog = false) {
        if (this.$refs.editorWrapper) {
          return this.$refs.editorWrapper;
        } else {
          if (showErrorDialog) {
            errorDialog({
              message: 'Editor is not initialized.',
            });
          }
          return undefined;
        }
      },
      onCopyCurrentCode() {
        const editorWrapper = this.checkEditorInitialized(true);
        if (editorWrapper) {
          saveTextToClipboard(editorWrapper.getCurrentCode());
        }
      },
      onPasteFromClipboard() {
        const editorWrapper = this.checkEditorInitialized(true);
        if (editorWrapper) {
          navigator.clipboard
            .readText()
            .then((text) => {
              editorWrapper.setCurrentCode(text);
              successDialog({
                message: 'Pasted code successfully',
              });
            })
            .catch((err) => {
              errorDialog({
                message: 'Failed to read clipboard contents. ' + err,
              });
            });
        }
      },
      onChangeVariableListOrientation() {
        const editorWrapper = this.checkEditorInitialized(true);
        if (editorWrapper) {
          editorWrapper.changeVariableListOrientation();
        }
      },
      onCallWorkSpace() {
        notAvailableMessage();
      },
      onEditorContentChanged(newCode) {
        this.updateCode(newCode);
      },
      onEditorInstanceLoaded() {
        this.loadedList.editor = true;
        this.$refs.editorWrapper.setCurrentCode(this.getCurrentCodeContent);
      },
      onCytoscapeInstanceLoaded() {
        this.loadedList.cytoscape = true;
      },
    },
    watch: {
      currentJsonArr: function() {
        this.resetContent();
      },
      getCurrentCodeObject: function() {
        if (this.$refs.editorWrapper) {
          this.$refs.editorWrapper.clearEditorDecoration();
          this.$refs.editorWrapper.setCurrentCode(this.getCurrentCodeContent);
          this.resetContent();
        }
      },
    },
  };
</script>
